openapi: "3.0.1"
info:
    title: API DOCS
    description: This is the DTS api documentation.
    version: "1.0"
    
servers:
  - url: "http://localhost:3000"
    description: local

x-tagGroups:
  - name: Users
    tags:
      - Users
  - name: Groups
    tags:
      - Groups
  - name: Files
    tags:
      - Files

paths:

# users

  /api/users/:
        post:
          summary: Registers new user to the system.
          tags:
            - Users
          requestBody:
            description: Registration Request
            required: true
            content:
               application/json:
                schema:
                  properties:
                    userName:
                      type: string
                      description: ontain only letters (both uppercase and lowercase), digits, underscores, or hyphens.
                      example: Valid_UserNAme1
                    email:
                      type: string
                      example: myEmail@example.com
                    password: 
                      type: string
                      description: Contain at least one lowercase letter.
                                   Contain at least one uppercase letter.
                                   Contain at least one digit.
                                   Be at least 8 characters long.
                      example: Password123
          responses:
            200:
              description: Success
            201:
              description: Success
            400:
              description: Bad Request
            500:
              description: Internal Server Error 
  /api/users/login:
        post:
          summary: Logs in a user.
          tags:
            - Users
          requestBody:
            description: log in Request
            required: true
            content:
               application/json:
                schema:
                  properties:
                    email:
                      type: string
                    password:
                      type: string
          responses:
            200:
              description: Success
            400:
              description: Bad Request
            500:
              description: Internal Server Error

  /api/users:
    get:
      summary: Returns users.
      tags:
        - Users
      parameters:
        - in: header
          name: auth
          schema:
            type: string
          required: true
      responses:
        200:
          description: Success
        400:
          description: Bad Request
        500:
          description: Internal Server Error

  /api/users/{userId}:
      get:
        summary: Returns user.
        tags:
          - Users
        parameters:
        - in: header
          name: auth
          schema:
            type: string
          required: true
        - in: path
          name: userId
          schema:
            type: integer
          required: true
        responses:
          200:
            description: Success
          400:
            description: Bad Request
          500:
            description: Internal Server Error

  #groups

  /api/groups/:
        post:
          summary: Creates new group in the system.
          tags:
            - Groups
          parameters:
          - in: header
            name: auth
            schema:
              type: string
            required: true
          requestBody:
            description: new group Request
            required: true
            content:
               application/json:
                schema:
                  properties:
                    groupName:
                      type: string
                    isPublic:
                      type: boolean
          responses:
            200:
              description: Success
            201:
              description: Success
            400:
              description: Bad Request
            500:
              description: Internal Server Error   

  /api/groups/ownership:
          get:
            summary: Returns groups that the user has created them.
            tags:
              - Groups
            parameters:
            - in: header
              name: auth
              schema:
                type: string
              required: true
            responses:
              200:
                description: Success
              400:
                description: Bad Request
              500:
                description: Internal Server Error  

  /api/groups/membership:
          get:
            summary: Returns groups that the user is member of.
            tags:
              - Groups
            parameters:
            - in: header
              name: auth
              schema:
                type: string
              required: true
            responses:
              200:
                description: Success
              400:
                description: Bad Request
              500:
                description: Internal Server Error   

  /api/groups/public:
          get:
            summary: Returns the public groups.
            tags:
              - Groups
            parameters:
            - in: header
              name: auth
              schema:
                type: string
              required: true
            responses:
              200:
                description: Success
              400:
                description: Bad Request
              500:
                description: Internal Server Error   

  /api/groups/search/{groupName}:
          get:
            summary: Search for public groups by name.
            tags:
              - Groups
            parameters:
            - in: header
              name: auth
              schema:
                type: string
              required: true
            - in: path
              name: groupName
              schema:
                type: string
              required: true
            responses:
              200:
                description: Success
              400:
                description: Bad Request
              500:
                description: Internal Server Error   

  /api/groups/{groupId}/users:
          get:
            summary: Returns users whom members of the group.
            tags:
              - Groups
            parameters:
            - in: header
              name: auth
              schema:
                type: string
              required: true
            - in: path
              name: groupId
              schema:
                type: integer
              required: true
            responses:
              200:
                description: Success
              400:
                description: Bad Request
              500:
                description: Internal Server Error   

  /api/groups/{groupId}:
          delete:
            summary: Delete a group from the system.
            tags:
              - Groups
            parameters:
            - in: header
              name: auth
              schema:
                type: string
              required: true
            - in: path
              name: groupId
              schema:
                type: integer
              required: true
            responses:
              200:
                description: Success
              400:
                description: Bad Request
              500:
                description: Internal Server Error   

  /api/groups/users:
          post:
            summary: Add user to a group.
            tags:
              - Groups
            parameters:
            - in: header
              name: auth
              schema:
                type: string
              required: true
            requestBody:
              description: Adding user Request
              required: true
              content:
                application/json:
                  schema:
                    properties:
                      groupId:
                        type: integer
                      userId:
                        type: integer
            responses:
              200:
                description: Success
              400:
                description: Bad Request
              500:
                description: Internal Server Error   

  /api/groups/{groupId}/users/{userId}:
          delete:
            summary: Remove user from a group.
            tags:
              - Groups
            parameters:
            - in: header
              name: auth
              schema:
                type: string
              required: true
            - in: path
              name: groupId
              schema:
                type: integer
              required: true
            - in: path
              name: userId
              schema:
                type: integer
              required: true              
            responses:
              200:
                description: Success
              400:
                description: Bad Request
              500:
                description: Internal Server Error   


  /api/groups/membership/:
          post:
            summary: User joins a public group.
            tags:
              - Groups
            parameters:
            - in: header
              name: auth
              schema:
                type: string
              required: true
            requestBody:
              description: Adding user Request
              required: true
              content:
                application/json:
                  schema:
                    properties:
                      groupId:
                        type: integer
            responses:
              200:
                description: Success
              400:
                description: Bad Request
              500:
                description: Internal Server Error   

  /api/groups/{groupId}/membership:
          delete:
            summary: User leaves a group.
            tags:
              - Groups
            parameters:
            - in: header
              name: auth
              schema:
                type: string
              required: true
            - in: path
              name: groupId
              schema:
                type: integer
              required: true           
            responses:
              200:
                description: Success
              400:
                description: Bad Request
              500:
                description: Internal Server Error   


# files
  /api/files:
          post:
            summary: upload a new file to a group.
            tags:
              - Files
            parameters:
            - in: header
              name: auth
              schema:
                type: string
              required: true
            requestBody:
              description: file Request
              required: true
              content:
                multipart/form-data:
                  schema:
                    type: object
                    properties:
                      groupId:
                        type: integer
                      file:
                        type: string
                        format: binary
            responses:
              200:
                description: Success
              400:
                description: Bad Request
              500:
                description: Internal Server Error   

  /api/files/{groupId}/{fileId}:
          delete:
            summary: Delete file.
            tags:
              - Files
            parameters:
            - in: header
              name: auth
              schema:
                type: string
              required: true
            - in: path
              name: groupId
              schema:
                type: integer
              required: true
            - in: path
              name: fileId
              schema:
                type: integer
              required: true              
            responses:
              200:
                description: Success
              400:
                description: Bad Request
              500:
                description: Internal Server Error   

  /api/files/{groupId}:
          get:
            summary: Returns files from a group.
            tags:
              - Files
            parameters:
            - in: header
              name: auth
              schema:
                type: string
              required: true
            - in: path
              name: groupId
              schema:
                type: integer
              required: true
            responses:
              200:
                description: Success
              400:
                description: Bad Request
              500:
                description: Internal Server Error   

  /api/files/storage/{filePath}:
            get:
              summary: Open file.
              description: Enter the file path starting from files_data.
              tags:
                - Files
              parameters:
              - in: header
                name: auth
                schema:
                  type: string
                required: true
              - in: path
                name: filePath
                schema:
                  type: string
                required: true         
              responses:
                200:
                  description: Success
                  content:
                    application/pdf:
                      schema:
                        type: string
                        format: binary
                    application/msword:
                      schema:
                        type: string
                        format: binary                     
                400:
                  description: Bad Request
                500:
                  description: Internal Server Error
  /api/files/search/{groupId}/{fileName}:
          get:
            summary: Search for files in a group by name.
            tags:
              - Files
            parameters:
            - in: header
              name: auth
              schema:
                type: string
              required: true
            - in: path
              name: groupId
              schema:
                type: integer
              required: true
            - in: path
              name: fileName
              schema:
                type: string
              required: true              
            responses:
              200:
                description: Success
              400:
                description: Bad Request
              500:
                description: Internal Server Error   

  /api/files/{groupId}/checkIn:
          post:
            summary: check in a file.
            description: to check multiple files at once split the IDs with a comma like this 1,2,3 .
            tags:
              - Files
            parameters:             
            - in: header
              name: auth
              schema:
                type: string
              required: true
            - in: query
              name: fileIds
              schema:
                type: string
              required: true              
            - in: path
              name: groupId
              schema:
                type: integer
              required: true                      
            responses:
              200:
                description: Success
              400:
                description: Bad Request
              403:
               description: Forbidden
              500:
                description: Internal Server Error   

  /api/files/{groupId}/{fileId}/checkOut:
          post:
            summary: check out a file.
            tags:
              - Files
            parameters:
            - in: header
              name: auth
              schema:
                type: string
              required: true
            - in: path
              name: groupId
              schema:
                type: integer
              required: true
            - in: path
              name: fileId
              schema:
                type: integer
              required: true              
            responses:
              200:
                description: Success
              400:
                description: Bad Request
              500:
                description: Internal Server Error                   

  /api/files/{groupId}/{fileId}/bookings:
          get:
            summary: Returns booking history of a file.
            tags:
              - Files
            parameters:
            - in: header
              name: auth
              schema:
                type: string
              required: true
            - in: path
              name: groupId
              schema:
                type: integer
              required: true
            - in: path
              name: fileId
              schema:
                type: integer
              required: true              
            responses:
              200:
                description: Success
              400:
                description: Bad Request
              500:
                description: Internal Server Error                   

  /api/files/{groupId}/{fileId}/archived:
          get:
            summary: Returns archived files.
            tags:
              - Files
            parameters:
            - in: header
              name: auth
              schema:
                type: string
              required: true
            - in: path
              name: groupId
              schema:
                type: integer
              required: true
            - in: path
              name: fileId
              schema:
                type: integer
              required: true              
            responses:
              200:
                description: Success
              400:
                description: Bad Request
              500:
                description: Internal Server Error       

  /api/files/{groupId}/{fileId}/update:
          post:
            summary: update file.
            tags:
              - Files
            parameters:
            - in: header
              name: auth
              schema:
                type: string
              required: true
            - in: path
              name: groupId
              schema:
                type: integer
              required: true
            - in: path
              name: fileId
              schema:
                type: integer
              required: true    
            requestBody:
              description: file Request
              required: true
              content:
                multipart/form-data:
                  schema:
                    type: object
                    properties:
                      file:
                        type: string
                        format: binary
                              
            responses:
              200:
                description: Success
              400:
                description: Bad Request
              500:
                description: Internal Server Error                       